### Pandas Function

In [3]:
import pandas as pd

csv_1 = pd.read_csv("G:\\Pandas\\restaurants.csv")

csv_1

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
0,410,21206,Frankford,2,NORTHEASTERN,"4509 BELAIR ROAD\nBaltimore, MD\n"
1,1919,21231,Fells Point,1,SOUTHEASTERN,"1919 FLEET ST\nBaltimore, MD\n"
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n"
4,#1 chinese restaurant,21223,Millhill,9,SOUTHWESTERN,"2481 frederick ave\nBaltimore, MD\n"
...,...,...,...,...,...,...
1322,ZEN WEST ROADSIDE CANTINA,21212,Rosebank,4,NORTHERN,"5916 YORK RD\nBaltimore, MD\n"
1323,ZIASCOS,21231,Washington Hill,1,SOUTHEASTERN,"1313 PRATT ST\nBaltimore, MD\n"
1324,ZINK'S CAF,21213,Belair-Edison,13,NORTHEASTERN,"3300 LAWNVIEW AVE\nBaltimore, MD\n"
1325,ZISSIMOS BAR,21211,Hampden,7,NORTHERN,"1023 36TH ST\nBaltimore, MD\n"
1326,ZORBAS,21224,Greektown,2,SOUTHEASTERN,"4710 EASTERN Ave\nBaltimore, MD\n"

In [3]:
csv_1.index

RangeIndex(start=0, stop=1327, step=1)

In [4]:
csv_1.columns

Index(['name', 'zipCode', 'neighborhood', 'councilDistrict', 'policeDistrict',
       'Location 1'],
      dtype='object')

In [6]:
csv_1.describe()

            zipCode  councilDistrict
count   1327.000000      1327.000000
mean   21184.787491         7.191409
std     1165.169261         4.518721
min   -21226.000000         1.000000
25%    21202.000000         2.000000
50%    21218.000000         9.000000
75%    21225.500000        11.000000
max    21287.000000        14.000000

In [11]:
csv_1.head()
# csv_1.head(2)

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
0,410,21206,Frankford,2,NORTHEASTERN,"4509 BELAIR ROAD\nBaltimore, MD\n"
1,1919,21231,Fells Point,1,SOUTHEASTERN,"1919 FLEET ST\nBaltimore, MD\n"
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n"
4,#1 chinese restaurant,21223,Millhill,9,SOUTHWESTERN,"2481 frederick ave\nBaltimore, MD\n"

In [14]:
csv_1.tail()
# csv_1.tail(2)

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
1322,ZEN WEST ROADSIDE CANTINA,21212,Rosebank,4,NORTHERN,"5916 YORK RD\nBaltimore, MD\n"
1323,ZIASCOS,21231,Washington Hill,1,SOUTHEASTERN,"1313 PRATT ST\nBaltimore, MD\n"
1324,ZINK'S CAF,21213,Belair-Edison,13,NORTHEASTERN,"3300 LAWNVIEW AVE\nBaltimore, MD\n"
1325,ZISSIMOS BAR,21211,Hampden,7,NORTHERN,"1023 36TH ST\nBaltimore, MD\n"
1326,ZORBAS,21224,Greektown,2,SOUTHEASTERN,"4710 EASTERN Ave\nBaltimore, MD\n"

In [15]:
csv_1[:3]

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
0,410,21206,Frankford,2,NORTHEASTERN,"4509 BELAIR ROAD\nBaltimore, MD\n"
1,1919,21231,Fells Point,1,SOUTHEASTERN,"1919 FLEET ST\nBaltimore, MD\n"
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"

In [16]:
csv_1[2:23]

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n"
4,#1 chinese restaurant,21223,Millhill,9,SOUTHWESTERN,"2481 frederick ave\nBaltimore, MD\n"
5,19TH HOLE,21218,Clifton Park,14,NORTHEASTERN,"2722 HARFORD RD\nBaltimore, MD\n"
6,3 KINGS,21205,McElderry Park,13,SOUTHEASTERN,"2510 MCELDERRY ST\nBaltimore, MD\n"
7,"3 MILES HOUSE, INC.",21211,Remington,7,NORTHERN,"2701 MILES AVE\nBaltimore, MD\n"
8,3 W'S TAVERN,21205,McElderry Park,13,SOUTHEASTERN,"2518 MONUMENT ST\nBaltimore, MD\n"
9,300 SOUTH ANN STREET,21231,Upper Fells Point,1,SOUTHEASTERN,"300 ANN ST\nBaltimore, MD\n"
10,438 CLUB,21226,Curtis Bay,10,SOUTHERN,"1600 HAZEL ST\nBaltimore, MD\n"
11,5-MILE HOUSE,21215,Woodmere,5,NORTHWESTERN,"5302 REISTERSTOWN RD\nBaltimore, MD\n"
12,"743 S. MONTFORD,INC.",21224,Canton,1,SOUTHEASTERN,"743 MONTFORD ST\nBaltimore, MD\n"
13,A & W RESTAURANT,21224,Pulaski Industrial Area,1,SOUTHEASTERN,"5625 O DONNELL ST\nBaltimore, MD\n"
14,A TASTE OF CHINA,21202,Downtown,11,CENTRAL,"219 BALTIMORE ST\nBaltimore, MD\n"
15,ABACROMBIE FINE FOODS,21201,Mid-Town Belvedere,11,CENTRAL,"58 BIDDLE STREET\nBaltimore, MD\n"
16,ABC SUSHI,21205,Middle East,13,EASTERN,"2003 MONUMENT ST\nBaltimore, MD\n"
17,ACROPOLIS RESTAURANT,21224,Greektown,2,SOUTHEASTERN,"4718 EASTERN AVE\nBaltimore, MD\n"
18,ADMIRAL FELL INN,21231,Fells Point,1,SOUTHEASTERN,"818 BROADWAY\nBaltimore, MD\n"
19,AG & HARP'S,21230,Morrell Park,10,SOUTHWESTERN,"2522 WASHINGTON BLVD\nBaltimore, MD\n"
20,"AIRPORT BAR & GRILL, INC.",21222,Saint Helena,1,SOUTHEASTERN,"6500 RIVERVIEW AVE\nBaltimore, MD\n"
21,AKBAR RESTAURANT,21201,Mount Vernon,11,CENTRAL,"823 CHARLES ST\nBaltimore, MD\n"
22,"AKDEY SUBWAY, INC.",21223,Millhill,9,SOUTHWESTERN,"2407 FREDERICK AVE\nBaltimore, MD\n"

In [17]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [18]:
csv_1.index.array

<NumpyExtensionArray>
[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
 ...
 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326]
Length: 1327, dtype: int64

In [19]:
csv_1.to_numpy()

array([['410', 21206, 'Frankford', 2, 'NORTHEASTERN',
        '4509 BELAIR ROAD\nBaltimore, MD\n'],
       ['1919', 21231, 'Fells Point', 1, 'SOUTHEASTERN',
        '1919 FLEET ST\nBaltimore, MD\n'],
       ['SAUTE', 21224, 'Canton', 1, 'SOUTHEASTERN',
        '2844 HUDSON ST\nBaltimore, MD\n'],
       ...,
       ["ZINK'S CAF\x90", 21213, 'Belair-Edison', 13, 'NORTHEASTERN',
        '3300 LAWNVIEW AVE\nBaltimore, MD\n'],
       ['ZISSIMOS BAR', 21211, 'Hampden', 7, 'NORTHERN',
        '1023 36TH ST\nBaltimore, MD\n'],
       ['ZORBAS', 21224, 'Greektown', 2, 'SOUTHEASTERN',
        '4710 EASTERN Ave\nBaltimore, MD\n']],
      shape=(1327, 6), dtype=object)

In [22]:
import numpy as np

v = np.asarray(csv_1)
v

array([['410', 21206, 'Frankford', 2, 'NORTHEASTERN',
        '4509 BELAIR ROAD\nBaltimore, MD\n'],
       ['1919', 21231, 'Fells Point', 1, 'SOUTHEASTERN',
        '1919 FLEET ST\nBaltimore, MD\n'],
       ['SAUTE', 21224, 'Canton', 1, 'SOUTHEASTERN',
        '2844 HUDSON ST\nBaltimore, MD\n'],
       ...,
       ["ZINK'S CAF\x90", 21213, 'Belair-Edison', 13, 'NORTHEASTERN',
        '3300 LAWNVIEW AVE\nBaltimore, MD\n'],
       ['ZISSIMOS BAR', 21211, 'Hampden', 7, 'NORTHERN',
        '1023 36TH ST\nBaltimore, MD\n'],
       ['ZORBAS', 21224, 'Greektown', 2, 'SOUTHEASTERN',
        '4710 EASTERN Ave\nBaltimore, MD\n']],
      shape=(1327, 6), dtype=object)

In [23]:
csv_1.sort_index(axis=0,ascending=False)

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
1326,ZORBAS,21224,Greektown,2,SOUTHEASTERN,"4710 EASTERN Ave\nBaltimore, MD\n"
1325,ZISSIMOS BAR,21211,Hampden,7,NORTHERN,"1023 36TH ST\nBaltimore, MD\n"
1324,ZINK'S CAF,21213,Belair-Edison,13,NORTHEASTERN,"3300 LAWNVIEW AVE\nBaltimore, MD\n"
1323,ZIASCOS,21231,Washington Hill,1,SOUTHEASTERN,"1313 PRATT ST\nBaltimore, MD\n"
1322,ZEN WEST ROADSIDE CANTINA,21212,Rosebank,4,NORTHERN,"5916 YORK RD\nBaltimore, MD\n"
...,...,...,...,...,...,...
4,#1 chinese restaurant,21223,Millhill,9,SOUTHWESTERN,"2481 frederick ave\nBaltimore, MD\n"
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n"
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"
1,1919,21231,Fells Point,1,SOUTHEASTERN,"1919 FLEET ST\nBaltimore, MD\n"
0,410,21206,Frankford,2,NORTHEASTERN,"4509 BELAIR ROAD\nBaltimore, MD\n"

In [ ]:
csv_1.loc[0,"zipCode"]=11111
csv_1

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1,Pincode,"(0, zipCode)"
0,410,11111,Frankford,2,NORTHEASTERN,"4509 BELAIR ROAD\nBaltimore, MD\n",11111.0,11111
1,1919,21231,Fells Point,1,SOUTHEASTERN,"1919 FLEET ST\nBaltimore, MD\n",NaN,11111
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n",NaN,11111
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n",NaN,11111
4,#1 chinese restaurant,21223,Millhill,9,SOUTHWESTERN,"2481 frederick ave\nBaltimore, MD\n",NaN,11111
...,...,...,...,...,...,...,...,...
1322,ZEN WEST ROADSIDE CANTINA,21212,Rosebank,4,NORTHERN,"5916 YORK RD\nBaltimore, MD\n",NaN,11111
1323,ZIASCOS,21231,Washington Hill,1,SOUTHEASTERN,"1313 PRATT ST\nBaltimore, MD\n",NaN,11111
1324,ZINK'S CAF,21213,Belair-Edison,13,NORTHEASTERN,"3300 LAWNVIEW AVE\nBaltimore, MD\n",NaN,11111
1325,ZISSIMOS BAR,21211,Hampden,7,NORTHERN,"1023 36TH ST\nBaltimore, MD\n",NaN,11111
1326,ZORBAS,21224,Greektown,2,SOUTHEASTERN,"4710 EASTERN Ave\nBaltimore, MD\n",NaN,11111

In [33]:
csv_1.loc[[2,3],["zipCode","policeDistrict"]]

  zipCode policeDistrict
2   21224   SOUTHEASTERN
3   21211       NORTHERN

In [8]:
csv_1.loc[[2,3],:]
# csv_1.loc[:,["zipCode","policeDistrict"]]

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n"

In [9]:
csv_1.iloc[1,2]

'Fells Point'

In [11]:
csv_1.drop("councilDistrict", axis=1)
csv_1.drop(0,axis=0)

,name,zipCode,neighborhood,councilDistrict,policeDistrict,Location 1
1,1919,21231,Fells Point,1,SOUTHEASTERN,"1919 FLEET ST\nBaltimore, MD\n"
2,SAUTE,21224,Canton,1,SOUTHEASTERN,"2844 HUDSON ST\nBaltimore, MD\n"
3,#1 CHINESE KITCHEN,21211,Hampden,14,NORTHERN,"3998 ROLAND AVE\nBaltimore, MD\n"
4,#1 chinese restaurant,21223,Millhill,9,SOUTHWESTERN,"2481 frederick ave\nBaltimore, MD\n"
5,19TH HOLE,21218,Clifton Park,14,NORTHEASTERN,"2722 HARFORD RD\nBaltimore, MD\n"
...,...,...,...,...,...,...
1322,ZEN WEST ROADSIDE CANTINA,21212,Rosebank,4,NORTHERN,"5916 YORK RD\nBaltimore, MD\n"
1323,ZIASCOS,21231,Washington Hill,1,SOUTHEASTERN,"1313 PRATT ST\nBaltimore, MD\n"
1324,ZINK'S CAF,21213,Belair-Edison,13,NORTHEASTERN,"3300 LAWNVIEW AVE\nBaltimore, MD\n"
1325,ZISSIMOS BAR,21211,Hampden,7,NORTHERN,"1023 36TH ST\nBaltimore, MD\n"
1326,ZORBAS,21224,Greektown,2,SOUTHEASTERN,"4710 EASTERN Ave\nBaltimore, MD\n"